fix for new containers

diff --git a/.github/workflows/deploy-to-acr.yml b/.github/workflows/deploy-to-acr.yml
--- a/.github/workflows/deploy-to-acr.yml
+++ b/.github/workflows/deploy-to-acr.yml
@@ -58,13 +58,17 @@ jobs:
       - name: Check if tag exists in ACR
         id: check_tag
         run: |
-            EXISTING_TAG=$(az acr repository show-tags --name ${{ inputs.acr-registry }} --repository ${{ inputs.image-name }} --query "[?contains(@, '${{ inputs.tag }}')]" -o tsv)
-            if [ -n "$EXISTING_TAG" ]; then
-              echo "Tag '${{ inputs.tag }}' already exists in ACR. Aborting push to prevent accidental overwrite."
-              exit 1
-            else
-              echo "No existing tag '${{ inputs.tag }}' found. Proceeding..."
-            fi
+              if ! az acr repository show --name ${{ inputs.acr-registry }} --repository ${{ inputs.image-name }} &> /dev/null; then
+                echo "Repository '${{ inputs.image-name }}' not found in ACR. Proceeding with push..."
+              else
+                EXISTING_TAG=$(az acr repository show-tags --name ${{ inputs.acr-registry }} --repository ${{ inputs.image-name }} --query "[?contains(@, '${{ inputs.tag }}')]" -o tsv)
+                if [ -n "$EXISTING_TAG" ]; then
+                  echo "Tag '${{ inputs.tag }}' already exists in ACR. Aborting push to prevent accidental overwrite."
+                  exit 1
+                else
+                  echo "No existing tag '${{ inputs.tag }}' found. Proceeding..."
+                fi
+              fi
 
       - name: Push Docker image to ACR
         run: |
